services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs.db:/app/logs.db
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
